version: '3.9'

services:
  api:
    build:
      context: .
      dockerfile: ./Backend/API/YemekhaneApp.Api/Dockerfile

  frontend:
    build:
      context: .
      dockerfile: ./UI/YemekhaneApp.Frontend/Dockerfile
